---

- name: Upload logstash config file
  become: yes
  become_user: root
  template:
    src: logstash.conf.j2
    dest: "{{ LOGSTASH_CONF_FILE_PATH }}"
  when: LOGSTASH_CONF_FILE_PATH|length > 0
  tags: 
    - upload-config

- name: Run ELK stack in docker containers
  become: yes
  become_user: root
  docker_service:
    project_name: ELK
    definition:
      version: '2'
      services:
        elk:
          image: sebp/elk
          ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
  
  register: output

#- debug:
#    var: output
