---

- name: Run ELK stack in docker containers
  become: yes
  become_user: root
  docker_service:
    project_name: ELK
    definition:
      version: '2'
      services:
        elk:
          image: sebp/elk
          ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
  
  register: output
